services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cenur
      POSTGRES_PASSWORD: cenur_pass
      POSTGRES_DB: cenur_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    working_dir: /app
    # image: python:3.12-slim
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://cenur:cenur_pass@db:5432/cenur_db
      PYTHONPATH: /app
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./uploads:/app/uploads
      - ./alembic.ini:/app/alembic.ini
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"

volumes:
  pgdata:
