version: "3.9"

networks:
  depagua:
    driver: bridge

volumes:
  pgdata:

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cenur
      POSTGRES_PASSWORD: cenur_pass
      POSTGRES_DB: cenur_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - depagua
    ports:
      - "5432:5432"

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://cenur:cenur_pass@db:5432/cenur_db
      PYTHONPATH: /app
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
      - ./backend/uploads:/app/uploads
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/requirements.txt:/app/requirements.txt
      - ./backend/scripts:/app/scripts
      - ./backend/tests:/app/tests
      - ./certs:/certs:ro
    networks:
      - depagua
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - web
    volumes:
      - ./frontend:/app
      - ./certs:/certs:ro
    networks:
      - depagua
    ports:
      - "443:443"

  pg_backup:
    image: prodrigestivill/postgres-backup-local:15-alpine
    container_name: pg_backup
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: cenur_db
      POSTGRES_DBS: cenur_db
      POSTGRES_USER: cenur
      POSTGRES_PASSWORD: cenur_pass
      POSTGRES_EXTRA_OPTS: "--schema=public --blobs"
      SCHEDULE: "0 6 * * *"
      TZ: America/Montevideo
      BACKUP_KEEP_DAYS: "7"
    volumes:
      - ./backups:/backups
    networks:
      - depagua
