services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cenur
      POSTGRES_PASSWORD: cenur_pass
      POSTGRES_DB: cenur_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    working_dir: /app
    # image: python:3.12-slim
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://cenur:cenur_pass@db:5432/cenur_db
      PYTHONPATH: /app
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./uploads:/app/uploads
      - ./alembic.ini:/app/alembic.ini
      - ./requirements.txt:/app/requirements.txt
      - ./scripts:/app/scripts
      - ./tests:/app/tests
      - ./certs:/certs:ro
    ports:
      - "443:8000"

  pg_backup:
    image: prodrigestivill/postgres-backup-local:15-alpine # incluye pg_dump + cron
    container_name: pg_backup
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: cenur_db
      POSTGRES_USER: cenur
      POSTGRES_PASSWORD: cenur_pass
      POSTGRES_EXTRA_OPTS: "--schema=public --blobs"
      SCHEDULE: "0 6 * * *" # 06:00 todos los días
      TZ: America/Montevideo
      # Retención opcional (7 días); ajusta si hace falta
      BACKUP_KEEP_DAYS: "7"
    volumes:
      - ./backups:/backups # ← repositorio local tangible

volumes:
  pgdata:
