"""add admin table

Revision ID: 8377de3440bf
Revises: 2c4f73fbc5b4
Create Date: 2025-06-02 13:18:43.399035

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8377de3440bf'
down_revision = '2c4f73fbc5b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.alter_column('blogpost', 'publicado',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogpost', 'publicado',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_table('admin')
    # ### end Alembic commands ###
