"""Initial migration

Revision ID: 9ccd2c8ca70d
Revises:
Create Date: 2024-05-28 13:40:00.000000

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9ccd2c8ca70d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actividad",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("fecha", sa.Date(), nullable=True),
        sa.Column("resultado_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "archivo",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("ruta", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column("tamano", sa.Integer(), nullable=True),
        sa.Column("fecha_subida", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "equipamiento",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("marca", sa.String(), nullable=True),
        sa.Column("modelo", sa.String(), nullable=True),
        sa.Column("n_serie", sa.String(), nullable=True),
        sa.Column("hoja_especificaciones_url", sa.String(), nullable=True),
        sa.Column("fecha_adquisicion", sa.Date(), nullable=True),
        sa.Column("estado", sa.String(), nullable=True),
        sa.Column("ubicacion", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "personal",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("cargo", sa.String(), nullable=True),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("foto_url", sa.String(), nullable=True),
        sa.Column("cv_url", sa.String(), nullable=True),
        sa.Column("orcid", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("fecha_alta", sa.Date(), nullable=True),
        sa.Column("fecha_baja", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "proyecto",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("fecha_inicio", sa.Date(), nullable=True),
        sa.Column("fecha_fin", sa.Date(), nullable=True),
        sa.Column("financiador", sa.String(), nullable=True),
        sa.Column("presupuesto", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "publicacion",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("cita_formateada", sa.String(), nullable=True),
        sa.Column("doi_url", sa.String(), nullable=True),
        sa.Column("enlace_pdf", sa.String(), nullable=True),
        sa.Column("anio", sa.Integer(), nullable=True),
        sa.Column("estado", sa.String(), nullable=True),
        sa.Column("fecha_registro", sa.DateTime(), nullable=False),
        sa.Column("authors", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "servicio",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("publico_objetivo", sa.String(), nullable=True),
        sa.Column("tarifa", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "equipamientoactividad",
        sa.Column("equipamiento_id", sa.Integer(), nullable=False),
        sa.Column("actividad_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actividad_id"],
            ["actividad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["equipamiento_id"],
            ["equipamiento.id"],
        ),
        sa.PrimaryKeyConstraint("equipamiento_id", "actividad_id"),
    )
    op.create_table(
        "personalproyecto",
        sa.Column("personal_id", sa.Integer(), nullable=False),
        sa.Column("proyecto_id", sa.Integer(), nullable=False),
        sa.Column("rol", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["personal_id"],
            ["personal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyecto.id"],
        ),
        sa.PrimaryKeyConstraint("personal_id", "proyecto_id"),
    )
    op.create_table(
        "servicioequipamiento",
        sa.Column("servicio_id", sa.Integer(), nullable=False),
        sa.Column("equipamiento_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipamiento_id"],
            ["equipamiento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["servicio_id"],
            ["servicio.id"],
        ),
        sa.PrimaryKeyConstraint("servicio_id", "equipamiento_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("servicioequipamiento")
    op.drop_table("personalproyecto")
    op.drop_table("equipamientoactividad")
    op.drop_table("servicio")
    op.drop_table("publicacion")
    op.drop_table("proyecto")
    op.drop_table("personal")
    op.drop_table("equipamiento")
    op.drop_table("archivo")
    op.drop_table("actividad")
    # ### end Alembic commands ###
