"""change_publicacion_authors_to_jsonb

Revision ID: b110a17a7f53
Revises: 002_timestamp_with_tz
Create Date: 2025-05-29 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "b110a17a7f53"
down_revision = "002_timestamp_with_tz"  # Adjusted to the correct previous revision
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "publicacion",
        "authors",
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="authors::jsonb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "publicacion",
        "authors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using="authors::text",
    )
    # ### end Alembic commands ###
