name: Test FastAPI Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: cenur
          POSTGRES_PASSWORD: cenur_pass
          POSTGRES_DB: cenur_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install aiosqlite pytest pytest-asyncio pytest-cov httpx

      - name: Set up test environment
        run: |
          echo "DATABASE_URL=postgresql+psycopg2://cenur:cenur_pass@localhost:5432/cenur_test" > .env

      - name: Run tests
        run: |
          pytest -q

      - name: Generate coverage report
        run: |
          pytest --cov=app --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
